# Generated by Django 4.2 on 2023-08-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=20)),
                ('contest_date', models.DateTimeField(auto_now_add=True)),
                ('contest_author', models.CharField(max_length=20)),
            ],
        ),
    ]
