# Generated by Django 4.2 on 2023-08-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contest_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newcontest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newcontest_name', models.CharField(max_length=20)),
                ('newcontest_date', models.DateTimeField(auto_now_add=True)),
                ('newcontest_author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contest_testCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('newcontest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.newcontest')),
            ],
        ),
        migrations.CreateModel(
            name='Contest_Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('newcontest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.newcontest')),
            ],
        ),
        migrations.CreateModel(
            name='Contest_problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('compexity', models.TextField(max_length=20)),
                ('constraints', models.TextField(max_length=20)),
                ('categories', models.ManyToManyField(to='home.category')),
                ('newcontest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.newcontest')),
                ('tags', models.ManyToManyField(to='home.tag')),
            ],
        ),
    ]
