# Generated by Django 4.2 on 2023-08-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_cadmin_cauthor_alter_cadmin_cname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cproblem',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='cproblem',
            name='tags',
        ),
        migrations.AddField(
            model_name='cproblem',
            name='categories',
            field=models.TextField(default='Easy'),
        ),
        migrations.AddField(
            model_name='cproblem',
            name='tags',
            field=models.TextField(default='Math'),
        ),
    ]
