# Generated by Django 4.2 on 2023-08-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_cproblem_categories_remove_cproblem_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.CharField(max_length=50)),
                ('Newcontest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.newcontest')),
            ],
        ),
    ]
