# Generated by Django 4.2 on 2023-08-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdate',
            old_name='Newcontest',
            new_name='newcontest',
        ),
    ]
