# Generated by Django 4.2 on 2023-08-22 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_newcontest_cdate_newcontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupdatetestcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('cproblem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cproblem')),
            ],
        ),
        migrations.CreateModel(
            name='Cupdatesolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('cproblem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cproblem')),
            ],
        ),
    ]
