# Generated by Django 4.2 on 2023-08-24 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_submitestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussitem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
