# Generated by Django 4.2 on 2023-08-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_discussitem_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('cproblem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cproblem')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user_detail')),
            ],
        ),
    ]
