# Generated by Django 4.2 on 2023-08-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_myubmission_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myubmission',
            name='verdict',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
