# Generated by Django 4.2 on 2023-08-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_myubmission_newcontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myubmission',
            name='newcontest',
        ),
    ]
