# Generated by Django 4.2 on 2023-08-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_usercontestsub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usercontestsub',
        ),
    ]
