# Generated by Django 4.2 on 2023-08-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_myubmission_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploreitem',
            name='link',
            field=models.TextField(default='abc'),
        ),
    ]
