# Generated by Django 4.2.4 on 2023-09-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_exploreitem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploreitem',
            name='link',
            field=models.TextField(default='http://www.abc.com'),
        ),
        migrations.AlterField(
            model_name='myubmission',
            name='memorytaken',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='myubmission',
            name='timetaken',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='usercontestsub',
            name='memorytaken',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='usercontestsub',
            name='timetaken',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
